### ISSUE TITLE
not work well  at Android 4.1 webview

### ISSUE THREAD

**Issue by kingda** [rodneyrehm/viewport-units-buggyfill#100]
when i test vw on XIAOMI 2A,one phone made in China , the style  seemed  to be broken out.So i try to fix it by myself  in exploring your code, and i found that css rules style property don't contain css property which use unit with vw in XIAOMI webview. It resulted that some css rules in the style that the buggyfill.js made missed some css rules but only have content css rule, so how can i make some ways to fix it? thanks ~

**Comment by rodneyrehm** [comment]
The buggyfill *does not add* support for viewport units, it *merely fixes existing* the support that already existed. According to [caniuse](https://caniuse.com/#search=viewport-units) the first Android version to support viewport units was 4.4 - so I'm not surprised that Android 4.1 is not behaving as you expected.

If I misunderstood your problem, please re-open this issue :)

**Comment by kingda** [comment]
Thanks for your  answer ~ i think that my problem was not opening the “Access-Control-Allow-Origin” header for my static domain and put the "viewport-units-buggyfill-hacks.js" before the "viewport-units-buggyfill.js".After fixing it ,it work well at MI 2A.
