### ISSUE TITLE
Relative path issue

### ISSUE THREAD

**Issue by ryanburnette** [rodneyrehm/viewport-units-buggyfill#105]
I've got an issue for you. I include fonts from my own CDN sometimes. They have relative URL's in there that work when they're CSS, but when this library loads them it looks like the browser thinks the relative paths should be relative to the current host.

Probably related to the XHR loading of CSS.

If you're interested I should be able to whip up a reduced complexity example.

**Comment by rodneyrehm** [comment]
Can you separate the fonts into their own stylesheet? then you can exclude that from processing as [the docs suggest](https://github.com/rodneyrehm/viewport-units-buggyfill#using-viewport-units-buggyfill):

> To exempt certain stylesheets from being processed, the attribute `data-viewport-units-buggyfill="ignore"`:
> ```html
> <link rel="stylesheet" href="file-to-ignore.css" data-viewport-units-buggyfill="ignore">
> <link rel="stylesheet" href="file-to-process.css">
> ```

**Comment by ryanburnette** [comment]
It looks like the best approach might be to put the styles that need the buggyfill right in the head and ignore all external stylesheets.
