### ISSUE TITLE
OS X Safari < 7.1 has the vh bug

### ISSUE THREAD

**Issue by danieldunderfelt** [rodneyrehm/viewport-units-buggyfill#22]
Hey!

I noticed Safari versions lower than 7.1 also has the vh bug, so this script should also target OS X Safari.

**Comment by calebfaruki** [comment]
I've attempted to use this fix. However, when I init the buggyfill for Safari, I get a "no access-control-allow-origin header is present" error.

**Comment by rodneyrehm** [comment]
that sounds like you're loading the CSS off a different origin but haven't configured CORS headers properly…
