### ISSUE TITLE
Breaks in IE10 on Windows 7

### ISSUE THREAD

**Issue by gregorybolkenstijn** [rodneyrehm/viewport-units-buggyfill#37]
![screen shot 2015-01-15 at 15 46 28](https://cloud.githubusercontent.com/assets/683497/5759414/17fb8aca-9cce-11e4-8cf9-af405582b197.png)

The script completely breaks my website when viewed in IE10 on Windows 7 (in VirtualBox). I attached a screenshot of what's going wrong and the errors it throws. It's working fine in IE9 on Windows 7 and IE11 on Windows 8.1, both in VirtualBox as well.

**Comment by rodneyrehm** [comment]
seems to be the same problem that was reported in #21 and fixed with [v0.5.0](https://github.com/rodneyrehm/viewport-units-buggyfill/releases/tag/v0.5.0). I assume you're running an older version…

**Comment by gregorybolkenstijn** [comment]
I was running 0.4.1 indeed. Updating to 0.5.0 fixed the issue, thanks.
