### ISSUE TITLE
Buggyfill Hack: Safari 7.0 and older and Chrome 26 and older don't support viewport units in calc() expressions 

### ISSUE THREAD

**Issue by bastiantowers** [rodneyrehm/viewport-units-buggyfill#41]
According to http://caniuse.com/#search=calc , Safari 7.0 and older and Chrome 26 and older don't support viewport units in calc() expressions.

Is Buggyfill detecting this issue?

I've tried to use hacks to solve it, but it seems is not working on calc() functions.

To give an example, my CSS looks something like this:

.class{
    left: calc(50% - 11vh);
    top: calc(50% + 25vh);
    content: 'viewport-units-buggyfill; left: calc(50% - 53px); top: calc(50% - 117px);';
}

I've tried it on an iPhone4 with iOS7 and the hack is not overwritting the top and left property as supposed.

Is there anything I'm doing wrong? Or Buggyfill is not detecting the viewport units in calc() functions as not supported??

**Comment by rodneyrehm** [comment]
> I've tried to use hacks to solve it, but it seems is not working on calc() functions.

Did you pass in the hacks as [explained](https://github.com/rodneyrehm/viewport-units-buggyfill#using-viewport-units-buggyfill)?
Which version are you using?

> ```css
.class{
left: calc(50% - 11vh);
top: calc(50% + 25vh);
content: 'viewport-units-buggyfill; left: calc(50% - 53px); top: calc(50% - 117px);';
}
```

you're not using viewport-units in that example.

This hack was added by @zoltan-dulac and works fine on my end.

**Comment by bastiantowers** [comment]
Hi Rodney!

Yes, I passed it as explained. I'm using it on an Ionic app, over Angular.
The version I'm using is the 0.4.1.

So, do I have to write down the same in the content property, to force the hack? I thought it was some sort of fallback to declare the exact position you want in case of a fail. I think it's me and I did not understood the documentation. So, is Buggyfill aware of this situation with the calc function on iOS?

Thank you for your time!

**Comment by rodneyrehm** [comment]
> The version I'm using is the 0.4.1.

You're using an old version of the library with the new API introduced in [v0.5.0](https://github.com/rodneyrehm/viewport-units-buggyfill/releases/tag/v0.5.0). No wonder this isn't working.

> I think it's me and I did not understood the documentation.

We didn't put too much effort into documenting things - if you want to call the Readme a documentation. I don't think it's you. Feel free to provide your opinion on what the docs should say.

> So, is Buggyfill aware of this situation with the calc function on iOS?

yes.
