### ISSUE TITLE
Buggyfill not working on Safari 5.1.7 on Windows 7

### ISSUE THREAD

**Issue by EloyTheLab** [rodneyrehm/viewport-units-buggyfill#49]
I'm having a problem with Safari 5.1.7 on Windows 7, even when I use the force:true option.
Just to make it easier and avoid coding errors I'm trying with the vh.html example and I get it working on SRWare Iron Versión 40.0.2150.0, Chrome 42.0.2311.90 m and IE11, but not in Safari.

Safari UserAgent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2

I'm also having this problem on some android platforms but I don't know what I'm doing wrong or what's happening because I don't get any errors of any kind.

Any help is really appreciated :)

Thanks in advance!

**Comment by rodneyrehm** [comment]
> I'm having a problem with Safari 5.1.7 on Windows 7

As far as I understand it Safari for Windows has been discontinued years ago. I have no idea why you would want to run this browser at all. That said, Safari 5 did not support viewport units at all, so this buggyfill won't help. It only fixes existing features, not provide them to unaware browsers.

> I'm also having this problem on some android platforms

Similar issue. The Android Browser (not Chrome for Android, different story!) started supporting viewport units with Android 4.4. I guess you can use the content hack to get some support from the buggyfill.

**Comment by EloyTheLab** [comment]
Thanks for your fast reply.

So, the key is it only fixies existing features. Then I misunderstood something from how it works... sorry.

I'll give the content hack a try.

Best regards.
