### ISSUE TITLE
Error on iOS8 without set force to true

### ISSUE THREAD

**Issue by adriancervoni** [rodneyrehm/viewport-units-buggyfill#50]
Hi! first of all thanks fot that code, it works like a charm, the only thing is that I don't wan't to force the buggyfill in browsers that support vh and vw correctly, but on the iOS7, if I don't force it, it fails on the vh units, any idea why?

**Comment by rodneyrehm** [comment]
a) which version are you using?
b) please provide the UA string of the failing device

**Comment by adriancervoni** [comment]
Hi @rodneyrehm
a) v0.5.1
b) Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4

**Comment by rodneyrehm** [comment]
> v0.5.1

v0.5.3 is the latest.

> Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4 

that's iOS 8.1.3, not iOS 7. The buggyfill does not initialize for iOS8, because there's nothing to fix.

**Comment by adriancervoni** [comment]
You are right, it's iOS8, anyway I have incorrect measure of 100vh if I don't force the buggyfill to true, I have tested with and without and they give me different heights, sure there is no problem with iOS8/Safari6??

**Comment by rodneyrehm** [comment]
There is only one thing I'm aware of, but that doesn't really qualify as a bug: #35 - does that fit your bill?

**Comment by adriancervoni** [comment]
Yep, exactly that :( +1:

**Comment by rodneyrehm** [comment]
you can force only for iOS8, btw. see [the iOS ua sniffing](https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L37-L48) to figure out how to identify iOS8. If you're on iOS8, pass `{force: true}`, otherwise `{force: false}` for default behavior.

**Comment by adriancervoni** [comment]
Oh! didn't see that, I will try it now, thanks @rodneyrehm!

**Comment by adriancervoni** [comment]
I finally change the return:
```return iOSversion && iOSversion.length>1 && parseInt(iOSversion[1]) < 8;```

To set to true also the iOS8:
```return iOSversion && iOSversion.length>1 && parseInt(iOSversion[1]) <=8;```

Instead of sniff in another point of the script. 
Thanks!

**Comment by rodneyrehm** [comment]
While you're free to do that, proper package management would disallow that. By making changes to the original source you're locked into that version. How would you update to the next version? Anyway, whatever works for you is fine by me…

**Comment by adriancervoni** [comment]
Yes, you are right, I have used it as a test patch, thanks!
