### ISSUE TITLE
Conflicting with fonts.googleapis.com

### ISSUE THREAD

**Issue by Mottl** [rodneyrehm/viewport-units-buggyfill#55]
Not working if css from google apis have been used:
```html
<link href='http://fonts.googleapis.com/css?family=Roboto:100,300%7CRoboto+Condensed:300&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
```

**Comment by rodneyrehm** [comment]
please add the attribute `data-viewport-units-buggyfill="ignore"` and try again.

**Comment by Mottl** [comment]
Dear Rodney!

Thanks a lot for your help! I apologize I haven't say my thank immediately.
