### ISSUE TITLE
Overpowered IE11 check breaks client-supported properties

### ISSUE THREAD

**Issue by radium-v** [rodneyrehm/viewport-units-buggyfill#56]
Hi,

The check [here](https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L86) causes issues when using units other than `vmax`. Rather than taking a sledgehammer/all-or-nothing approach, this check should be made later on to determine if `vmax` support is necessary, and should only apply fixes for `vmax`.

```javascript
// added check for IE11, since it *still* doesn't understand vmax!!!
  if (!isBuggyIE) {
    isBuggyIE = !!navigator.userAgent.match(/Trident.*rv[ :]*11\./);
  }
```

**Comment by rodneyrehm** [comment]
how do you figure "check should be made later on" would work out?
