### ISSUE TITLE
Chrome test

### ISSUE THREAD

**Issue by simonccarter** [rodneyrehm/viewport-units-buggyfill#59]
First off, thanks for the great project!

I'm testing a website on an old phone using Chrome.

I notice if I comment out the if block starting at

https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L59 

then it runs, as the line at https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L59 returns true. If I leave it uncommented, it doesn't run (as the if block at https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L111 is entered). I guess my question relates to the comment: 

`this buggyfill only applies to mobile safari, IE9-10 and the Stock Android Browser.`

Can I ask why the tests have been set up to not run at least in this specific case? I'm not sure I follow the reasoning behind simple test for Chrome, and preventing this polyfill from doing it's work if it is.

The chrome version i'm running is 18.0.1025469 with the Android version being 4.1.1. 

Thanks again!

**Comment by rodneyrehm** [comment]
Your question is kinda hard to understand. Are you wondering why the buggyfill is not running on Chrome 18 for Android? I don't really know, as [caniuse](http://caniuse.com/#search=viewport) says nothing about viewport unit support for that version, so I assume it is not supported in Chrome 18 for Android. If they are supported, but buggy, we should fix the UA sniffing.

**Comment by simonccarter** [comment]
My bad. I forgot this is a buggyfill and not a polyfill. 

Basically, both my android browser and chrome for android browser versions don't support viewport units, but the hacks (with no calcs) run for the stock android browser, and not chrome. 

I guess this lead to me mistaking this project for a polyfil when it's not.

**Comment by rodneyrehm** [comment]
Yes, the hacks can be used to get *some* viewport-unit support into older browsers - but I can't say I'd recommend that. But I'm not using the hacks at all, so who am I to judge? You're free to send a PR to make the "polyfill" behavior simpler and more transparent, if you like.
