### ISSUE TITLE
Custom event for processing needed

### ISSUE THREAD

**Issue by redaxmedia** [rodneyrehm/viewport-units-buggyfill#62]
Hello,

old Android browsers usually have render issues while applying the viewport units hack.

For that reason I like to hide parts and show them once the hack was completed. Can you provide a custom event like <code>viewportUnitsBuggyfillPatched</code> that triggers on window? Maby other events are usefull too?

At the moment I obeserve the <code>#patched-viewport</code> what is kind of bad.

<pre>
$('#patched-viewport').on('DOMNodeInserted', function () {
    alert('viewportUnitsBuggyfillPatched');
});
</pre>

Thank you

**Comment by rodneyrehm** [comment]
You're welcome to send a pull request for this. You'd likely want a [CustomEvent](https://developer.mozilla.org/en/docs/Web/API/CustomEvent) called `viewport-units-buggyfill-style` to be emitted in the [updateStyles()](https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L151-L153) method.

**Comment by redaxmedia** [comment]
All right, will put this on my todo list.

**Comment by redaxmedia** [comment]
Pull request send, feel free to extend it with more :-)

**Comment by rodneyrehm** [comment]
released [v0.5.5](https://github.com/rodneyrehm/viewport-units-buggyfill/releases/tag/v0.5.5)
