### ISSUE TITLE
Chrome for ios wrong VH when keyboard is opened

### ISSUE THREAD

**Issue by Yuripetusko** [rodneyrehm/viewport-units-buggyfill#71]
On Chrome for ios when keyboard is revealed the VH is counted like there's 2 keyboards

I am doing `ViewPortBuggyFill.init({force: true});`

![img_1448](https://cloud.githubusercontent.com/assets/666169/17927560/28ba09ce-69ee-11e6-9dc2-976fe7174a06.PNG)

**Comment by Yuripetusko** [comment]
It is the same without bugyfill also, however if I do apply bugyfill and change orientation, it is fine after, so it looks like it doesn't recalculate when keyboard is revealed on Chrome for ios at all.

**Comment by rodneyrehm** [comment]
what happened to @Yuripetusko's comment

> It is the same without bugyfill also, however if I do apply bugyfill and change orientation, it is fine after, so it looks like it doesn't recalculate when keyboard is revealed on Chrome for ios at all.

?

**Comment by Yuripetusko** [comment]
Sorry false alarm! if I don't initialise buggyfill on chrome for ios everything is fine
