### ISSUE TITLE
Wrap in the module?

### ISSUE THREAD

**Issue by dartess** [rodneyrehm/viewport-units-buggyfill#80]
I do not use the package manager to store the connected resources, but I use gulp to build the project. Apparently, because of the above "strict mode", the string `} (this, function () {` was replaced with `} (undefined, function () {` and everything broke. I wrapped all the contents in an anonymous module `(function(){ ... })()`, this solved the problem. Be it worth adding your file so that its behavior can not be broken outside?

**Comment by rodneyrehm** [comment]
I've never heard of this problem before, but sure, adding an IIFE is benign enough. do you want to submit a PR for that?

**Comment by dartess** [comment]
If I format the code, it will change 100% of the file. This is normal? If yes, I will do pr.

**Comment by rodneyrehm** [comment]
you'll *add* two lines and everything else is a change in whitespace… that's totally fine.

in github you can view whitespace ignoring diffs by appending `?w=1` to the url. compare [regular diff](https://github.com/rodneyrehm/viewport-units-buggyfill/commit/e0884345a536130d0bda49e2580d3d10b239ed86) to [same diff without whitespace](https://github.com/rodneyrehm/viewport-units-buggyfill/commit/e0884345a536130d0bda49e2580d3d10b239ed86?w=1) - the latter omits 9 changes that only add/remove spaces.

**Comment by dartess** [comment]
https://github.com/rodneyrehm/viewport-units-buggyfill/pull/81

**Comment by rodneyrehm** [comment]
thank you!

we'll wait for a few other things to land before releasing the next version :)
