### ISSUE TITLE
Breaks fonts

### ISSUE THREAD

**Issue by ralphonz** [rodneyrehm/viewport-units-buggyfill#9]
As soon as I add window.viewportUnitsBuggyfill.init(); i get the following errors:

[Error] XMLHttpRequest cannot load http://fonts.googleapis.com/css?family=Roboto%3A300. Origin http://www.blueleafstudio.net is not allowed by Access-Control-Allow-Origin. (environmentally-friendly-web-hosting, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fontawesome-webfont.woff, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fontawesome-webfont.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fontawesome-webfont.svg, line 0)

It's looking for the fonts at http://www.blueleafstudio.net/fonts/fontawesome-webfont.woff?v=4.0.3 (which is my website) when it should be looking for them at http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css
The font starts loading fine and even renders until viewport-units-buggyfill kicks in.

**Comment by ryanburnette** [comment]
@rodneyrehm What exactly is this polyfill doing that breaks loading a stylesheet from an external domain without CORS headers?

**Comment by rodneyrehm** [comment]
@ryanburnette it fetches the the external stylesheet using XHR in order to import it into the document's origin in order to be able to access the CSSOM. But you can only fetch stuff from your own origin or from origins that allow your origin to download resources by way of setting proper CORS headers.
