### ISSUE TITLE
Can I change vw to rem?

### ISSUE THREAD

**Issue by hqqxxf** [rodneyrehm/viewport-units-buggyfill#90]

**Comment by hqqxxf** [comment]
@rodneyrehm

**Comment by rodneyrehm** [comment]
`rem` is a font-relative unit (as such not in scope of this project), `vw` is a viewport-relative unit. See https://developer.mozilla.org/en-US/docs/Web/CSS/length - If that does not answer your question, please elaborate what your actual problem is.
