### ISSUE TITLE
Server side import

### ISSUE THREAD

**Issue by Richacinas** [rodneyrehm/viewport-units-buggyfill#93]
Hello there,

I'm trying to use this library on a universal javascript application, and I get the error:

"window is not defined"

When Webpack is trying to compile es6 and bundle.

I'm guessing, there is no way to make this library work only client side??

Even just importing it, and not initializing, is throwing the error...

**Comment by Richacinas** [comment]
By now, I'm using the bundle and there is no problem anymore...

**Comment by samlogan** [comment]
Try this:

`const viewportUnitsBuggyfill = typeof window !== 'undefined' ? require('viewport-units-buggyfill') : null;`
