### ISSUE TITLE
Cannot load the corresponding background image.

### ISSUE THREAD

**Issue by ZeroJsus** [rodneyrehm/viewport-units-buggyfill#96]
In the mobile background image, polyfill cannot load the corresponding image.
`&::before{
     content:'';
     width: 50px;
     height: 50px;
     display: block;
     margin: 1px auto 0 auto;
     background-image: url('./../assets/images/footericon.png');
     background-repeat: no-repeat;
     background-size: 400%;
}`
Polyfill in the mobile background image cannot load the corresponding background image.

The error message : net::ERR_INVALID_URL

**Comment by rodneyrehm** [comment]
I don't quite understand the problem. The example code is not using any viewport units, so I don't see the problem. What does the DevTools say about the element's styles?

**Comment by ZeroJsus** [comment]
Thank you for answering my question. 😄 😄 😄 
I use vue this is a vue component in the update style should be due to the path problem causing the image to load failed.
Here's the wrong message.
`GET data:image/png;base64,iVBO...
Failed to load resource net::ERR_INVALID_URL
updateStyles @ viewport-units-buggyfill.js?708a:188
(anonymous) @ viewport-units-buggyfill.js?708a:205
`
So how do I fix this path?

**Comment by ZeroJsus** [comment]
Problem solved!!!
I use <script> instead of Require to use js without causing the image path error.
use `<script viewport-units-buggyfill.hacks.min.js,viewport-units-buggyfill.min.js"></script>`
